"$schema" = 'https://starship.rs/config-schema.json'

# Left
format = """
$username\
$hostname\
$directory\
${custom.nb}\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$python\
$lua\
$go\
$line_break\
$character"""

# Right
right_format = """$sudo $cmd_duration $jobs $time"""

# Inserts a blank line between shell prompts
add_newline = true

[directory]
style = "blue"
home_symbol = "~"
[character] 
success_symbol = '[󰁕](bold purple)' 
error_symbol = '[✖](bold red)'

[package]
disabled = true

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.nb]
detect_folders = ['.nb']
command = "cat ~/.nb/.current"
style = "bold white"
symbol = ""
format = "[$symbol $output]($style)"
